language: c
sudo: true 
dist: xenial


#addons:
#  apt:
#    packages:
#    - gcc-arm-none-eabi 

install:
    - sudo add-apt-repository ppa:team-gcc-arm-embedded/ppa
    - sudo apt-get update
    - sudo apt-get install gcc-arm-embedded

script: 
 #- cat yes yes | pros conduct download latest
 # - pros conduct new .
 - make
 
