language: c

install:
  - sudo apt-get install gcc-arm-none-eabi
  - sudo apt-get install python3
  - TEMP_DEB="$(mktemp)"
  - wget -O "$TEMP_DEB" 'https://github.com/purduesigbots/pros/releases/download/2.12.1/pros-core-2.6.1-amd64.deb'
  - sudo dpkg -i "$TEMP_DEB"
  - rm -f "$TEMP_DEB"
  
script: 
 - echoo 'Y' | pros conduct download
 - pros conduct new .
 - make
 
